import asyncio, os, re
import edge_tts

VOICE = "en-GB-SoniaNeural"

async def gen(out_dir, words):
    os.makedirs(out_dir, exist_ok=True)
    for fname, text in words.items():
        out = f"{out_dir}/{fname}.mp3"
        if os.path.exists(out):
            continue
        tts = edge_tts.Communicate(text, VOICE)
        await tts.save(out)
        print(f"OK: {fname}")

async def main():

    # Unit 3
    await gen("vocabulary/audio3", {
        "in_active": "active",
        "a_book_by_sb_about": "a book  about",
        "a_fan_of": "a fan of",
        "a_game_against": "a game against",
        "act": "act",
        "action": "action",
        "actor": "actor",
        "athlete": "athlete",
        "athletic": "athletic",
        "athletics": "athletics",
        "beat": "beat",
        "board_game": "board game",
        "bored_with": "bored with",
        "captain": "captain",
        "carry_on": "carry on",
        "challenge": "challenge",
        "champion": "champion",
        "cheat": "cheat",
        "child": "child",
        "childhood": "childhood",
        "children": "children",
        "classical_music": "classical music",
        "club": "club",
        "coach": "coach",
        "collect": "collect",
        "collection": "collection",
        "collector": "collector",
        "competition": "competition",
        "concert": "concert",
        "crazy_about": "crazy about",
        "defeat": "defeat",
        "eat_out": "eat out",
        "entertain": "entertain",
        "entertaining": "entertaining",
        "entertainment": "entertainment",
        "feel_like": "feel like",
        "folk_music": "folk music",
        "for_a_long_time": "for a long time",
        "for_fun": "for fun",
        "give_up": "give up",
        "good_at": "good at",
        "group": "group",
        "gym": "gym",
        "have_fun": "have fun",
        "hero": "hero",
        "heroic": "heroic",
        "heroine": "heroine",
        "in_the_middle_of": "in the middle",
        "in_time_for": "in time",
        "interest": "interest",
        "interested_in": "interested in",
        "join_in": "join in",
        "keen_on": "keen on",
        "listen_to": "listen to",
        "member": "member",
        "music": "music",
        "musical": "musical",
        "musician": "musician",
        "on_cd_dvd_video": "on cd or dvd or video",
        "on_stage": "on stage",
        "opponent": "opponent",
        "organise": "organise",
        "play": "play",
        "player": "player",
        "playful": "playful",
        "pleasure": "pleasure",
        "popular_with": "popular with",
        "referee": "referee",
        "rhythm": "rhythm",
        "risk": "risk",
        "sail": "sail",
        "sailing": "sailing",
        "sailor": "sailor",
        "sang": "sang",
        "score": "score",
        "send_off": "send off",
        "sing": "sing",
        "singer": "singer",
        "singing": "singing",
        "song": "song",
        "sung": "sung",
        "support": "support",
        "take_part_in": "take part in",
        "take_up": "take up",
        "team": "team",
        "train": "train",
        "turn_down": "turn down",
        "turn_up": "turn up",
        "video_game": "video game",
    })
    print("Unit 3 done")

    # Unit 6
    await gen("vocabulary/audio6", {
        "a_question_about": "a question about",
        "achieve": "achieve",
        "an_opinion_about_of": "an opinion about or of",
        "began": "began",
        "begin": "begin",
        "beginner": "beginner",
        "beginning": "beginning",
        "begun": "begun",
        "brain": "brain",
        "brave": "brave",
        "bravery": "bravery",
        "by_heart": "by heart",
        "capable_of": "capable of",
        "cheat_at_in": "cheat at or in",
        "clever": "clever",
        "concentrate": "concentrate",
        "confuse_sth_with": "confuse sth with",
        "consider": "consider",
        "continue_with": "continue with",
        "cope_with": "cope with",
        "correct": "correct",
        "correction": "correction",
        "course": "course",
        "cross_out": "cross out",
        "degree": "degree",
        "divide": "divide",
        "division": "division",
        "educate": "educate",
        "education": "education",
        "experience": "experience",
        "expert": "expert",
        "fail": "fail",
        "for_instance": "for instance",
        "guess": "guess",
        "help_sb_with": "help  with",
        "hesitate": "hesitate",
        "in_conclusion": "in conclusion",
        "in_fact": "in fact",
        "in_favour_of": "in favour",
        "in_general": "in general",
        "incorrect": "incorrect",
        "instruct": "instruct",
        "instruction": "instruction",
        "instructor": "instructor",
        "know_about": "know about",
        "learn_about": "learn about",
        "look_up": "look up",
        "make_progress": "make progress",
        "make_sure": "make sure",
        "mark": "mark",
        "memorial": "memorial",
        "memorise": "memorise",
        "memory": "memory",
        "mental": "mental",
        "pass": "pass",
        "point_out": "point out",
        "qualification": "qualification",
        "read_out": "read out",
        "refer": "refer",
        "reference": "reference",
        "remind": "remind",
        "report": "report",
        "revise": "revise",
        "rip_up": "rip up",
        "rub_out": "rub out",
        "search": "search",
        "silence": "silence",
        "silent": "silent",
        "silently": "silently",
        "simple": "simple",
        "simplicity": "simplicity",
        "simplify": "simplify",
        "skill": "skill",
        "smart": "smart",
        "subject": "subject",
        "succeed_in": "succeed in",
        "take_an_exam": "take an exam",
        "talented": "talented",
        "talented_at": "talented at",
        "term": "term",
        "turn_over": "turn over",
        "wonder": "wonder",
        "write_down": "write down",
    })
    print("Unit 6 done")

    # Unit 9
    await gen("vocabulary/audio9", {
        "abroad": "abroad",
        "accommodation": "accommodation",
        "arrive_at_in": "arrive at or in",
        "ask_sb_about": "ask  about",
        "ask_for": "ask for",
        "attract": "attract",
        "attraction": "attraction",
        "attractive": "attractive",
        "back": "back",
        "backwards": "backwards",
        "book": "book",
        "break": "break",
        "by_air_sea_bus_car_etc": "by air or sea or bus or car or etc",
        "cancel": "cancel",
        "catch": "catch",
        "choice": "choice",
        "choose": "choose",
        "chose": "chose",
        "chosen": "chosen",
        "close_to": "close to",
        "coach": "coach",
        "comfort": "comfort",
        "comfortable": "comfortable",
        "convenient": "convenient",
        "crash": "crash",
        "crowded": "crowded",
        "cruise": "cruise",
        "delay": "delay",
        "depart": "depart",
        "departure": "departure",
        "destination": "destination",
        "direct": "direct",
        "direction": "direction",
        "drive": "drive",
        "driven": "driven",
        "driver": "driver",
        "drove": "drove",
        "famous_for": "famous for",
        "far_from": "far from",
        "ferry": "ferry",
        "flew": "flew",
        "flight": "flight",
        "flown": "flown",
        "fly": "fly",
        "foreign": "foreign",
        "get_in_to": "get in",
        "get_off": "get off",
        "get_on_to": "get on",
        "get_out_of": "get out",
        "go_away": "go away",
        "go_back_to": "go back",
        "harbour": "harbour",
        "journey": "journey",
        "late_for": "late for",
        "look_at": "look at",
        "luggage": "luggage",
        "nearby": "nearby",
        "on_board": "on board",
        "on_foot": "on foot",
        "on_holiday": "on holiday",
        "on_schedule": "on schedule",
        "on_the_coast": "on the coast",
        "pack": "pack",
        "passport": "passport",
        "platform": "platform",
        "prepare_for": "prepare for",
        "provide_sb_with": "provide sb with",
        "public_transport": "public transport",
        "reach": "reach",
        "resort": "resort",
        "set_off": "set off",
        "souvenir": "souvenir",
        "suitable_for": "suitable for",
        "take_off": "take off",
        "traffic": "traffic",
        "travel": "travel",
        "traveller": "traveller",
        "trip": "trip",
        "uncomfortable": "uncomfortable",
        "vehicle": "vehicle",
        "visit": "visit",
        "visitor": "visitor",
        "wait_for": "wait for",
    })
    print("Unit 9 done")

    # Unit 12
    await gen("vocabulary/audio12", {
        "a_relationship_with": "a relationship with",
        "ability": "ability",
        "able": "able",
        "admiration": "admiration",
        "admire": "admire",
        "admire_sb_for": "admire sb for",
        "an_argument_with_sb_about": "an argument  about",
        "apologise": "apologise",
        "apologise_to_sb_for": "apologise  for",
        "argue_with_sb_about": "argue  about",
        "boyfriend": "boyfriend",
        "bring_up": "bring up",
        "by_yourself": "by yourself",
        "care": "care",
        "care_about": "care about",
        "careful": "careful",
        "careless": "careless",
        "chat_to_sb_about": "chat  about",
        "close": "close",
        "confidence": "confidence",
        "confident": "confident",
        "cool": "cool",
        "couple": "couple",
        "decorate": "decorate",
        "defend": "defend",
        "disabled": "disabled",
        "dishonest": "dishonest",
        "divorced": "divorced",
        "fall_out_with": "fall out",
        "flat": "flat",
        "fond_of": "fond of",
        "forgave": "forgave",
        "forgive": "forgive",
        "forgiven": "forgiven",
        "forgiveness": "forgiveness",
        "generous": "generous",
        "get_on_with": "get on",
        "girlfriend": "girlfriend",
        "go_out_with": "go out with",
        "grateful": "grateful",
        "grow_up": "grow up",
        "guest": "guest",
        "honest": "honest",
        "honesty": "honesty",
        "in_common_with": "in common",
        "in_contact_with": "in contact",
        "in_love_with": "in love",
        "independent": "independent",
        "introduce": "introduce",
        "introduction": "introduction",
        "jealous_of": "jealous of",
        "kind_to": "kind to",
        "let_down": "let down",
        "liar": "liar",
        "lie": "lie",
        "look_after": "look after",
        "loving": "loving",
        "loyal": "loyal",
        "lying": "lying",
        "married_to": "married to",
        "mood": "mood",
        "neighbourhood": "neighbourhood",
        "on_purpose": "on purpose",
        "on_your_own": "on your own",
        "ordinary": "ordinary",
        "patient": "patient",
        "person": "person",
        "personal": "personal",
        "personality": "personality",
        "private": "private",
        "proud_of": "proud of",
        "recognise": "recognise",
        "relate": "relate",
        "relation": "relation",
        "relationship": "relationship",
        "relative": "relative",
        "rent": "rent",
        "respect": "respect",
        "single": "single",
        "split_up": "split up",
        "stranger": "stranger",
        "trust": "trust",
        "unable": "unable",
    })
    print("Unit 12 done")

    # Unit 15
    await gen("vocabulary/audio15", {
        "in_expensive": "expensive",
        "add": "add",
        "add_up": "add up",
        "addition": "addition",
        "advertisement": "advertisement",
        "afford": "afford",
        "affordable": "affordable",
        "an_advert_isement_for": "an advert for",
        "bargain": "bargain",
        "belong_to": "belong to",
        "borrow_sth_from": "borrow sth from",
        "brand": "brand",
        "buy_sth_from": "buy sth from",
        "by_credit_card_cheque": "by credit card or cheque",
        "catalogue": "catalogue",
        "change": "change",
        "choose_between": "choose between",
        "coin": "coin",
        "come_back_from": "come back",
        "compare": "compare",
        "compare_sth_to_with": "compare sth to or with",
        "comparison": "comparison",
        "cost": "cost",
        "customer": "customer",
        "debt": "debt",
        "decide": "decide",
        "decide_on": "decide on",
        "decision": "decision",
        "demand": "demand",
        "expense": "expense",
        "export": "export",
        "fee": "fee",
        "for_rent": "for rent",
        "for_sale": "for sale",
        "fortune": "fortune",
        "give_away": "give away",
        "hurry_up": "hurry up",
        "import": "import",
        "in_cash": "in cash",
        "in_debt": "in debt",
        "in_good_bad_condition": "in good or bad condition",
        "invest": "invest",
        "judge": "judge",
        "judgement": "judgement",
        "lend_sth_to": "lend sth to",
        "obtain": "obtain",
        "owe": "owe",
        "own": "own",
        "pay_back": "pay back",
        "pay_for": "pay for",
        "profit": "profit",
        "property": "property",
        "purchase": "purchase",
        "receipt": "receipt",
        "require": "require",
        "sale": "sale",
        "save": "save",
        "save_up_for": "save up",
        "select": "select",
        "servant": "servant",
        "serve": "serve",
        "service": "service",
        "spend_sth_on": "spend sth on",
        "supply": "supply",
        "take_back": "take back",
        "take_down": "take down",
        "true": "true",
        "truth": "truth",
        "truthful": "truthful",
        "untrue": "untrue",
        "use": "use",
        "useful": "useful",
        "useless": "useless",
        "valuable": "valuable",
        "value": "value",
        "variety": "variety",
        "waste": "waste",
        "wrong_about_with": "wrong about or with",
    })
    print("Unit 15 done")

    # Unit 18
    await gen("vocabulary/audio18", {
        "a_difference_between": "a difference between",
        "a_number_of": "a number of",
        "a_reason_for": "a reason for",
        "a_type_of": "a type of",
        "an_idea_about": "an idea about",
        "artificial": "artificial",
        "at_last": "at last",
        "automatic": "automatic",
        "begin_sth_with": "begin sth with",
        "boil": "boil",
        "boiler": "boiler",
        "boiling": "boiling",
        "break_down": "break down",
        "by_chance": "by chance",
        "chemical": "chemical",
        "chemist": "chemist",
        "chemistry": "chemistry",
        "come_across": "come across",
        "complicated": "complicated",
        "conclude": "conclude",
        "conclusion": "conclusion",
        "connect_sth_to_with": "connect sth to or with",
        "decrease": "decrease",
        "different_from_to": "different from or to",
        "digital": "digital",
        "disconnect_sth_from": "disconnect sth from",
        "discover": "discover",
        "effect": "effect",
        "equipment": "equipment",
        "estimate": "estimate",
        "exact": "exact",
        "exam_ination": "exam",
        "examine": "examine",
        "examiner": "examiner",
        "experiment": "experiment",
        "fascinate": "fascinate",
        "fascinating": "fascinating",
        "fascination": "fascination",
        "fill_sth_with": "fill sth with",
        "find_out": "find out",
        "full_of": "full of",
        "gadget": "gadget",
        "hardware": "hardware",
        "historian": "historian",
        "historic": "historic",
        "history": "history",
        "identical": "identical",
        "identically": "identically",
        "in_my_opinion": "in my opinion",
        "in_the_end": "in the end",
        "in_the_future": "in the future",
        "invent": "invent",
        "involve": "involve",
        "laboratory": "laboratory",
        "lack": "lack",
        "laptop": "laptop",
        "length": "length",
        "long": "long",
        "make_up": "make up",
        "maximum": "maximum",
        "measure": "measure",
        "measurement": "measurement",
        "minimum": "minimum",
        "operate": "operate",
        "out_of_order": "out of order",
        "plastic": "plastic",
        "program": "program",
        "pull_off": "pull off",
        "research": "research",
        "result_in": "result in",
        "run": "run",
        "science": "science",
        "scientist": "scientist",
        "screen": "screen",
        "software": "software",
        "sudden": "sudden",
        "technology": "technology",
        "throw_away": "throw away",
        "turn_off": "turn off",
        "turn_on": "turn on",
        "unique": "unique",
    })
    print("Unit 18 done")

    # Unit 21
    await gen("vocabulary/audio21", {
        "un_predictable": "predictable",
        "a_letter_from_sb_about": "a letter  about",
        "accent": "accent",
        "announcement": "announcement",
        "broadcast": "broadcast",
        "by_e_mail_phone_letter": "by e-mail or phone or letter",
        "call_back": "call back",
        "certain": "certain",
        "certainly": "certainly",
        "certainty": "certainty",
        "channel": "channel",
        "clear": "clear",
        "click": "click",
        "come_out": "come out",
        "comment_on": "comment on",
        "communicate": "communicate",
        "communicate_with": "communicate with",
        "communication": "communication",
        "connect": "connect",
        "connection": "connection",
        "contact": "contact",
        "cut_off": "cut off",
        "deliver": "deliver",
        "delivery": "delivery",
        "disconnect": "disconnect",
        "express": "express",
        "expression": "expression",
        "expressive": "expressive",
        "file": "file",
        "fill_in": "fill in",
        "formal": "formal",
        "glance_at": "glance at",
        "hang_up": "hang up",
        "image": "image",
        "inform": "inform",
        "informal": "informal",
        "information": "information",
        "information_about": "information about",
        "informative": "informative",
        "internet": "internet",
        "interrupt": "interrupt",
        "link": "link",
        "log_off": "log off",
        "log_on_to": "log on",
        "media": "media",
        "mobile_phone": "mobile phone",
        "on_the_internet": "on the internet",
        "on_the_news": "on the news",
        "on_the_phone": "on the phone",
        "on_the_radio": "on the radio",
        "on_tv": "on tv",
        "online": "online",
        "pause": "pause",
        "persuade": "persuade",
        "predict": "predict",
        "prediction": "prediction",
        "print_out": "print out",
        "pronounce": "pronounce",
        "publish": "publish",
        "receive_sth_from": "receive sth from",
        "reply_to": "reply to",
        "report": "report",
        "request": "request",
        "ring": "ring",
        "secrecy": "secrecy",
        "secret": "secret",
        "secretly": "secretly",
        "send_sth_to_sb": "send sth to sb",
        "signal": "signal",
        "speak": "speak",
        "speaker": "speaker",
        "speech": "speech",
        "spoke": "spoke",
        "spoken": "spoken",
        "swear": "swear",
        "talk_to_sb_about": "talk  about",
        "tell_sb_about": "tell sb about",
        "translate": "translate",
        "translate_from_sth_into": "translate  into",
        "translation": "translation",
        "translator": "translator",
        "type": "type",
        "viewer": "viewer",
        "website": "website",
        "whisper": "whisper",
        "write_to_sb_about": "write  about",
    })
    print("Unit 21 done")

    # Unit 24
    await gen("vocabulary/audio24", {
        "inter_national": "national",
        "un_believable": "believable",
        "accuse_sb_of": "accuse sb of",
        "admit": "admit",
        "against_the_law": "against the law",
        "agree": "agree",
        "agreement": "agreement",
        "alive": "alive",
        "angry_with_sb_about": "angry  about",
        "arrest": "arrest",
        "at_the_age_of": "at the age of",
        "belief": "belief",
        "believe": "believe",
        "blame_sb_for": "blame sb for",
        "blame_sth_on": "blame sth on",
        "break_in_to": "break in",
        "catch_up_with": "catch up",
        "charity": "charity",
        "commit": "commit",
        "community": "community",
        "courage": "courage",
        "courageous": "courageous",
        "court": "court",
        "criminal": "criminal",
        "criticise_sb_for": "criticise sb for",
        "culture": "culture",
        "disagree": "disagree",
        "elect": "elect",
        "election": "election",
        "equal": "equal",
        "equality": "equality",
        "familiar": "familiar",
        "forget_about": "forget about",
        "forgive_sb_for": "forgive sb for",
        "get_away_with": "get away with",
        "get_up": "get up",
        "government": "government",
        "guilty_of": "guilty of",
        "habit": "habit",
        "identity_card": "identity card",
        "illegal": "illegal",
        "in_public": "in public",
        "in_response_to": "in response to",
        "in_touch_with": "in touch",
        "in_your_teens_twenties_etc": "in your teens or twenties or etc",
        "invite_sb_to": "invite sb to",
        "life": "life",
        "live": "live",
        "move_in": "move in",
        "nation": "nation",
        "nationality": "nationality",
        "peace": "peace",
        "peaceful_ly": "peaceful",
        "politics": "politics",
        "population": "population",
        "prison": "prison",
        "prisoner": "prisoner",
        "protest": "protest",
        "punish_sb_for": "punish sb for",
        "put_away": "put away",
        "resident": "resident",
        "responsible": "responsible",
        "rob": "rob",
        "routine": "routine",
        "schedule": "schedule",
        "share_sth_with": "share sth with",
        "shoot": "shoot",
        "shooting": "shooting",
        "shot": "shot",
        "situation": "situation",
        "smile_at": "smile at",
        "social": "social",
        "society": "society",
        "steal": "steal",
        "tradition": "tradition",
        "typical": "typical",
        "unequal": "unequal",
        "vote": "vote",
        "wake_up": "wake up",
        "wash_up": "wash up",
        "youth_club": "youth club",
    })
    print("Unit 24 done")

    # Unit 27
    await gen("vocabulary/audio27", {
        "un_employment": "employment",
        "un_official": "official",
        "un_successful": "successful",
        "a_kind_of": "a kind of",
        "ambition": "ambition",
        "application": "application",
        "apply_for": "apply for",
        "assist": "assist",
        "assistance": "assistance",
        "assistant": "assistant",
        "at_the_moment": "at the moment",
        "bank_account": "bank account",
        "beg": "beg",
        "beggar": "beggar",
        "boss": "boss",
        "bossy": "bossy",
        "call_off": "call off",
        "career": "career",
        "careful_with": "careful with",
        "colleague": "colleague",
        "company": "company",
        "contract": "contract",
        "department": "department",
        "depend_on": "depend on",
        "deserve": "deserve",
        "difficult_for": "difficult for",
        "earn": "earn",
        "employ": "employ",
        "employee": "employee",
        "employer": "employer",
        "fame": "fame",
        "famous": "famous",
        "fed_up_with": "fed up with",
        "give_back": "give back",
        "go_on": "go on",
        "goal": "goal",
        "impress": "impress",
        "in_charge_of": "in charge",
        "income": "income",
        "industry": "industry",
        "inform_sb_about": "inform sb about",
        "interview": "interview",
        "leader": "leader",
        "manager": "manager",
        "occupation": "occupation",
        "occupy": "occupy",
        "office": "office",
        "officer": "officer",
        "on_business": "on business",
        "on_strike": "on strike",
        "on_time": "on time",
        "on_off_duty": "on or off duty",
        "pension": "pension",
        "poverty": "poverty",
        "pressure": "pressure",
        "previous": "previous",
        "profession": "profession",
        "put_off": "put off",
        "ready_for": "ready for",
        "refer_to": "refer to",
        "responsible_for": "responsible for",
        "retire": "retire",
        "retired": "retired",
        "retirement": "retirement",
        "safe": "safe",
        "safety": "safety",
        "salary": "salary",
        "save": "save",
        "set_up": "set up",
        "staff": "staff",
        "stay_up": "stay up",
        "strike": "strike",
        "succeed": "succeed",
        "success": "success",
        "take_away": "take away",
        "take_over": "take over",
        "tax": "tax",
        "unemployed": "unemployed",
        "unsafe": "unsafe",
        "wealthy": "wealthy",
        "work_as": "work as",
        "work_for": "work for",
    })
    print("Unit 27 done")

    # Unit 30
    await gen("vocabulary/audio30", {
        "a_cure_for": "a cure for",
        "a_recipe_for": "a recipe for",
        "addicted_to": "addicted to",
        "affect": "affect",
        "allergic_to": "allergic to",
        "at_night": "at night",
        "at_risk": "at risk",
        "bake": "bake",
        "baker": "baker",
        "bakery": "bakery",
        "balance": "balance",
        "bend": "bend",
        "benefit": "benefit",
        "bent": "bent",
        "breathe": "breathe",
        "chew": "chew",
        "chop": "chop",
        "combine_sth_with": "combine sth with",
        "complain_to_sb_about": "complain  about",
        "contain": "contain",
        "cook": "cook",
        "cooker": "cooker",
        "cookery": "cookery",
        "cough": "cough",
        "covered_in_with": "covered in or with",
        "cure": "cure",
        "cut_down_on": "cut down",
        "die_from_of": "die from or of",
        "exercise": "exercise",
        "fall_down": "fall down",
        "fight_against": "fight against",
        "flu": "flu",
        "get_over": "get over",
        "go_off": "go off",
        "have_an_operation": "have an operation",
        "healthy": "healthy",
        "ignore": "ignore",
        "in_addition_to": "in addition",
        "in_comparison_to_with": "in comparison to or with",
        "in_shape": "in shape",
        "infection": "infection",
        "ingredient": "ingredient",
        "injury": "injury",
        "intend": "intend",
        "intention": "intention",
        "intentional": "intentional",
        "jog": "jog",
        "jogger": "jogger",
        "jogging": "jogging",
        "lie_down": "lie down",
        "limit": "limit",
        "meal": "meal",
        "medical": "medical",
        "medicine": "medicine",
        "on_a_diet": "on a diet",
        "pain": "pain",
        "painful": "painful",
        "painless": "painless",
        "pill": "pill",
        "pleased_with": "pleased with",
        "put_on": "put on",
        "recover": "recover",
        "recover_from": "recover from",
        "reduce": "reduce",
        "reduction": "reduction",
        "salty": "salty",
        "sense": "sense",
        "sensible": "sensible",
        "sensitive": "sensitive",
        "sit_down": "sit down",
        "slice": "slice",
        "smell_of": "smell of",
        "sour": "sour",
        "spicy": "spicy",
        "stand_up": "stand up",
        "stir": "stir",
        "suffer": "suffer",
        "taste": "taste",
        "treatment": "treatment",
        "vitamin": "vitamin",
        "weigh": "weigh",
        "weight": "weight",
    })
    print("Unit 30 done")

    # Unit 33
    await gen("vocabulary/audio33", {
        "un_breakable": "breakable",
        "a_picture_of": "a picture of",
        "amazed_at_by": "amazed at or by",
        "an_influence_on": "an influence on",
        "ancient": "ancient",
        "art": "art",
        "artist": "artist",
        "artistic": "artistic",
        "at_the_back_of": "at the back",
        "at_the_end_of": "at the end",
        "break": "break",
        "broke": "broke",
        "broken": "broken",
        "change_sth_from_sth_into": "change sth  into",
        "checked": "checked",
        "compose": "compose",
        "composer": "composer",
        "composition": "composition",
        "cotton": "cotton",
        "create": "create",
        "cut_off": "cut off",
        "describe_sth_as": "describe sth as",
        "design": "design",
        "disappointed_with": "disappointed with",
        "do_up": "do up",
        "exhibit": "exhibit",
        "exhibition": "exhibition",
        "explain_sth_to": "explain sth to",
        "familiar_with": "familiar with",
        "fill_up": "fill up",
        "fix": "fix",
        "fold": "fold",
        "free": "free",
        "freedom": "freedom",
        "gallery": "gallery",
        "hand": "hand",
        "handful": "handful",
        "handle": "handle",
        "have_on": "have on",
        "imagination": "imagination",
        "imaginative": "imaginative",
        "imagine": "imagine",
        "imperfect": "imperfect",
        "improvement": "improvement",
        "in_fashion_style": "in fashion or style",
        "in_front_of": "in front",
        "in_the_corner_of": "in the corner",
        "intelligence": "intelligence",
        "intelligent": "intelligent",
        "involved_in": "involved in",
        "leave_out": "leave out",
        "loose": "loose",
        "maintain": "maintain",
        "match": "match",
        "material": "material",
        "notice": "notice",
        "out_of_fashion_style": "out of fashion or style",
        "pattern": "pattern",
        "perfect": "perfect",
        "perfection": "perfection",
        "pile": "pile",
        "practical": "practical",
        "preparation": "preparation",
        "prepare": "prepare",
        "put_on": "put on",
        "remind_sb_of": "remind sb of",
        "remove_sth_from": "remove sth from",
        "rough": "rough",
        "shape": "shape",
        "silk": "silk",
        "similar_to": "similar to",
        "sleeve": "sleeve",
        "smooth": "smooth",
        "stretch": "stretch",
        "striped": "striped",
        "style": "style",
        "suit": "suit",
        "suitable": "suitable",
        "take_off": "take off",
        "tear": "tear",
        "tight": "tight",
        "tool": "tool",
        "try_on": "try on",
    })
    print("Unit 33 done")

    # Unit 36
    await gen("vocabulary/audio36", {
        "afraid_of": "afraid of",
        "amazing": "amazing",
        "an_increase_in": "an increase in",
        "at_most": "at most",
        "at_the_top_bottom_of": "at the top or bottom",
        "aware_of": "aware of",
        "blow_up": "blow up",
        "build_up": "build up",
        "central": "central",
        "centre": "centre",
        "circle": "circle",
        "circular": "circular",
        "clear_up": "clear up",
        "climate": "climate",
        "countryside": "countryside",
        "damage_to": "damage to",
        "danger": "danger",
        "dangerous": "dangerous",
        "deep": "deep",
        "deeply": "deeply",
        "depth": "depth",
        "destroy": "destroy",
        "destruction": "destruction",
        "destructive": "destructive",
        "enthusiastic_about": "enthusiastic about",
        "environment": "environment",
        "escape_from": "escape from",
        "extinct": "extinct",
        "fog": "fog",
        "foggy": "foggy",
        "forecast": "forecast",
        "freezing": "freezing",
        "garden": "garden",
        "gardener": "gardener",
        "gardening": "gardening",
        "global": "global",
        "go_out": "go out",
        "heatwave": "heatwave",
        "in_the_beginning": "in the beginning",
        "in_the_distance": "in the distance",
        "in_total": "in total",
        "insect": "insect",
        "invade": "invade",
        "invader": "invader",
        "invasion": "invasion",
        "keep_out": "keep out",
        "lightning": "lightning",
        "litter": "litter",
        "local": "local",
        "locate": "locate",
        "mammal": "mammal",
        "mild": "mild",
        "name": "name",
        "natural": "natural",
        "naturally": "naturally",
        "nature": "nature",
        "on_top_of": "on top",
        "origin": "origin",
        "planet": "planet",
        "pollute": "pollute",
        "polluted": "polluted",
        "pollution": "pollution",
        "preserve": "preserve",
        "prevent_sb_from": "prevent sb from",
        "put_down": "put down",
        "put_out": "put out",
        "put_up": "put up",
        "recycle": "recycle",
        "reptile": "reptile",
        "rescue": "rescue",
        "satellite": "satellite",
        "save_sth_from": "save sth from",
        "serious_about": "serious about",
        "short_of": "short of",
        "shower": "shower",
        "solar_system": "solar system",
        "species": "species",
        "think_about": "think about",
        "thunder": "thunder",
        "wild": "wild",
        "wildlife": "wildlife",
        "worry_about": "worry about",
    })
    print("Unit 36 done")

    # Unit 39
    await gen("vocabulary/audio39", {
        "un_happiness": "happiness",
        "a_joke_about": "a joke about",
        "amusing": "amusing",
        "annoy": "annoy",
        "ashamed_of": "ashamed of",
        "at_first": "at first",
        "at_least": "at least",
        "at_times": "at times",
        "attitude": "attitude",
        "bad_tempered": "bad-tempered",
        "behave": "behave",
        "bore": "bore",
        "bored": "bored",
        "boring": "boring",
        "bully": "bully",
        "calm": "calm",
        "calm_down": "calm down",
        "celebrate": "celebrate",
        "character": "character",
        "cheer_up": "cheer up",
        "come_on": "come on",
        "comedian": "comedian",
        "comedy": "comedy",
        "congratulate_sb_on": "congratulate sb on",
        "depressed": "depressed",
        "embarrassed_about": "embarrassed about",
        "embarrassing": "embarrassing",
        "emotion": "emotion",
        "emotional": "emotional",
        "energetic": "energetic",
        "energy": "energy",
        "enthusiastic": "enthusiastic",
        "excite": "excite",
        "excited": "excited",
        "excitement": "excitement",
        "exciting": "exciting",
        "feel": "feel",
        "feeling": "feeling",
        "feeling_s": "feeling",
        "felt": "felt",
        "frightened_of": "frightened of",
        "glad": "glad",
        "go_on": "go on",
        "hang_on": "hang on",
        "happy": "happy",
        "happy_about_with": "happy about or with",
        "hate": "hate",
        "hatred": "hatred",
        "hurt": "hurt",
        "in_secret": "in secret",
        "in_spite_of": "in spite of",
        "in_tears": "in tears",
        "laugh_at": "laugh at",
        "miserable": "miserable",
        "naughty": "naughty",
        "nervous_about": "nervous about",
        "noise": "noise",
        "noisily": "noisily",
        "noisy": "noisy",
        "polite": "polite",
        "react": "react",
        "regret": "regret",
        "ridiculous": "ridiculous",
        "romantic": "romantic",
        "rude": "rude",
        "run_away_from": "run away",
        "scared_of": "scared of",
        "sense_of_humour": "sense of humour",
        "shut_up": "shut up",
        "shy": "shy",
        "sorry_about_for": "sorry about or for",
        "speak_up": "speak up",
        "stress": "stress",
        "surprised_at_by": "surprised at or by",
        "sympathetic": "sympathetic",
        "sympathise": "sympathise",
        "sympathy": "sympathy",
        "tell_a_joke": "tell a joke",
        "tired_of": "tired of",
        "unhappy": "unhappy",
        "upset": "upset",
    })
    print("Unit 39 done")

    # Unit 42
    await gen("vocabulary/audio42", {
        "un_helpful": "helpful",
        "un_luckily": "luckily",
        "un_lucky": "lucky",
        "a_solution_to": "a solution to",
        "accident": "accident",
        "advice": "advice",
        "advise": "advise",
        "advise_against": "advise against",
        "adviser": "adviser",
        "agree_with_sb_about": "agree  about",
        "an_advantage_of": "an advantage of",
        "approve_of": "approve of",
        "assume": "assume",
        "believe_in": "believe in",
        "by_accident_mistake": "by accident or mistake",
        "cause": "cause",
        "claim": "claim",
        "complain": "complain",
        "confuse": "confuse",
        "confused": "confused",
        "confusion": "confusion",
        "convince": "convince",
        "criticise": "criticise",
        "deal_with": "deal with",
        "deny": "deny",
        "discussion": "discussion",
        "doubt": "doubt",
        "encourage": "encourage",
        "except": "except",
        "exception": "exception",
        "get_rid_of": "get rid of",
        "gossip": "gossip",
        "hang_up": "hang up",
        "happen_to": "happen to",
        "help": "help",
        "helpless": "helpless",
        "hide_sth_from_sb": "hide sth from sb",
        "ideal": "ideal",
        "in_a_mess": "in a mess",
        "in_danger_of": "in danger",
        "in_my_view": "in my view",
        "in_trouble": "in trouble",
        "insist_on": "insist on",
        "insult": "insult",
        "investigate": "investigate",
        "luck": "luck",
        "negative": "negative",
        "pick_up": "pick up",
        "positive": "positive",
        "praise": "praise",
        "prefer": "prefer",
        "preferable": "preferable",
        "preference": "preference",
        "pretend": "pretend",
        "purpose": "purpose",
        "put_back": "put back",
        "recommend": "recommend",
        "recommendation": "recommendation",
        "refusal": "refusal",
        "refuse": "refuse",
        "rely_on": "rely on",
        "result": "result",
        "rumour": "rumour",
        "run_out_of": "run out",
        "sensible": "sensible",
        "serious": "serious",
        "share_out": "share out",
        "solution": "solution",
        "solve": "solve",
        "sort_out": "sort out",
        "spare": "spare",
        "suggest": "suggest",
        "suggestion": "suggestion",
        "sure_about_of": "sure about or of",
        "theory": "theory",
        "thought": "thought",
        "under_pressure": "under pressure",
        "warn": "warn",
        "watch_out": "watch out",
        "work_out": "work out",
    })
    print("Unit 42 done")

asyncio.run(main())